FROM node:18 
# image created will me on node:18 which has linux and node js

WORKDIR /app
# setting the working directory to /app where the application code will reside

COPY package*.json ./
# copying package.json and package-lock.json to the working directory

RUN npm install
# installing the application dependencies

COPY server.js ./
# copying server.js to the working directory

EXPOSE 3000
# exposing port 3000 for the application 

CMD ["node", "server.js"]
# starting the application